export const MsgTypes = {
  SELECT_TYPE: "SELECT_TYPE",
  CLOSE_UI: "CLOSE_UI",
  LANGUAGE_INFO: "LANGUAGE_INFO",
  LANGUAGE_EDIT: "LANGUAGE_EDIT",
  CHECK_SELECT: "CHECK_SELECT",
  EXTRACT: "EXTRACT",
};
