const fontWeight = { bold: 700, medium: 500, regular: 400, regula: 400 };
const fonts = {
  heading1_B: {
    "font-size": "32px",
    "font-weight": fontWeight.bold,
    "line-height": "48px",
  },
  heading2_B: {
    "font-size": "24px",
    "font-weight": fontWeight.bold,
    "line-height": "32px",
  },
  heading3_B: {
    "font-size": "20px",
    "font-weight": fontWeight.bold,
    "line-height": "32px",
  },
  heading4_B: {
    "font-size": "18px",
    "font-weight": fontWeight.bold,
    "line-height": "28px",
  },
  heading5_B: {
    "font-size": "16px",
    "font-weight": fontWeight.bold,
    "line-height": "24px",
  },
  heading6_B: {
    "font-size": "14px",
    "font-weight": fontWeight.bold,
    "line-height": "24px",
  },
  body1_M: {
    "font-size": "18px",
    "font-weight": fontWeight.medium,
    "line-height": "28px",
  },
  body2_M: {
    "font-size": "16px",
    "font-weight": fontWeight.medium,
    "line-height": "24px",
  },
  body3_M: {
    "font-size": "14px",
    "font-weight": fontWeight.medium,
    "line-height": "24px",
  },
  body4_M: {
    "font-size": "12px",
    "font-weight": fontWeight.medium,
    "line-height": "18px",
  },
  body1_R: {
    "font-size": "18px",
    "font-weight": fontWeight.regular,
    "line-height": "28px",
  },
  body2_R: {
    "font-size": "16px",
    "font-weight": fontWeight.regular,
    "line-height": "24px",
  },
  body3_R: {
    "font-size": "14px",
    "font-weight": fontWeight.regular,
    "line-height": "24px",
  },
  body4_R: {
    "font-size": "12px",
    "font-weight": fontWeight.regula,
    "line-height": "18px",
  },
  button1: {
    "font-size": "18px",
    "font-weight": fontWeight.medium,
    "line-height": "22px",
  },
  button2: {
    "font-size": "16px",
    "font-weight": fontWeight.medium,
    "line-height": "20px",
  },
  button3: {
    "font-size": "14px",
    "font-weight": fontWeight.medium,
    "line-height": "16px",
  },
  button4: {
    "font-size": "12px",
    "font-weight": fontWeight.medium,
    "line-height": "14px",
  },
};
const color = {
  black: "#000000",
  text: "#242426",
  gray1: "#242426",
  gray2: "#464646",
  gray3: "#6E6E6E",
  gray4: "#8C8C8C",
  gray5: "#AAAAAA",
  input: "#CDCDCD",
  border: "#DCDCDC",
  gray6: "#CDCDCD",
  gray7: "#DCDCDC",
  gray8: "#EFEFEF",
  gray9: "#F8F8F8",
  white: "#FFFFFF",
  secondary1: "#2A0B65",
  secondary2: "#4A14B0",
  default: "#6A1CFC",
  secondary3: "#6A1CFC",
  secondary4: "#8341F9",
  secondary5: "#A678FB",
  hover: "#C4A4FC",
  secondary6: "#C4A4FC",
  secondary7: "#E7DAFE",
  secondary8: "#F3ECFF",
  secondary9: "#F7F5FF",
  adminRed1: "#BE0000",
  adminRed2: "#D20000",
  adminred3: "#E60000",
  adminRed4: "#FF6464",
  adminRed5: "#FEE5E6",
  adminRed6: "#FFF8F7",
  adminOrange1: "#FF9500",
  adminOrange2: "#FFA905",
  adminOrange3: "#FFBF66",
  adminOrange4: "#FFDFB3",
  adminOrange5: "#FFF4E5",
  adminYellow1: "#E1AE00",
  adminYellow2: "#FFCC00",
  adminYellow3: "#FFE066",
  adminYellow4: "#FFF0B3",
  adminYellow5: "#FFF9E2",
  adminGreen1: "#006E1D",
  adminGreen2: "#009645",
  adminGreen3: "#86DF9C",
  adminGreen4: "#C2EFCE",
  adminGreen5: "#E4FBEA",
  adminTeal1: "#3CAADC",
  adminTeal2: "#5AC8FA",
  adminTeal3: "#93D8FF",
  adminTeal4: "#CDEEFE",
  adminTeal5: "#E6F7FE",
  adminBlue1: "#005CE1",
  adminBlue2: "#007AFF",
  adminBlue3: "#52A5FF",
  adminBlue4: "#B3D7FF",
  adminBlue5: "#E5F2FF",
};
